file_in = open('rosalind_ini5.txt','r')
read = file_in.read()
#Cursor goes back to the file top by .seek(0)
file_in.seek(0)
readline = file_in.readline()
file_in.seek(0)
readlines = file_in.readlines()
#Difference between .read, .readline and .readlines
print(read)
type(read)
print('---------')
print(readline)
type(readline)
print('---------')
print(readlines)
type(readlines)
file_in.close()